import { strict as assert } from 'node:assert';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { test } from 'node:test';
import { createApp } from '../server.js';
import { addBlockMusic, createBlock, createMusic, addSource, openDatabase } from '../src/db/repositories.js';

function fixture() { const root=mkdtempSync(join(tmpdir(),'live-console-f8-1-')); mkdirSync(join(root,'musicas')); mkdirSync(join(root,'videos')); writeFileSync(join(root,'musicas','ok.mp3'),'audio'); writeFileSync(join(root,'videos','ok.mp4'),'video'); const db=openDatabase(join(root,'db.sqlite')); const app=createApp({database:db,storageRoot:root}); return {root,db,app}; }
function item(song:string, source:string, title:string, base:string) { return {musicaId:song,versaoId:source,titulo:title,artista:'Artista',musicaBase:base,duracao:120,xEmLives:3}; }

test('F8.1 reserva abertura por musicaId, remove-a apenas do bloco e preserva a ordem', async () => {
  const {db,app}=fixture(); const opening=createMusic(db,{artista:'Artista',titulo:'Abertura',ativo:true,xEmLives:9,musicaBase:'base-abertura'}); const openingSource=addSource(db,opening,{nome:'Abertura',tipo:'youtube',referencia:'https://youtu.be/open',abertura:true,principal:true}); const middle=createMusic(db,{artista:'Artista',titulo:'Meio',ativo:true,musicaBase:'base-meio'}); const middleSource=addSource(db,middle,{nome:'Áudio',tipo:'audio',referencia:'musicas/ok.mp3',principal:true}); const end=createMusic(db,{artista:'Artista',titulo:'Fim',ativo:true,musicaBase:'base-fim'}); const endSource=addSource(db,end,{nome:'Vídeo',tipo:'video',referencia:'videos/ok.mp4',principal:true}); const block=createBlock(db,{nome:'Bloco com abertura'}); addBlockMusic(db,block,opening); addBlockMusic(db,block,middle); addBlockMusic(db,block,end);
  const draft=(await app.inject({method:'POST',url:'/api/v1/live-drafts'})).json<any>().rascunho; const option=draft.opcoes.blocos.find((x:any)=>x.id===block); assert.deepEqual(option.itens.map((x:any)=>x.musicaId),[opening,middle,end]); const payload={abertura:{musicaId:opening,versaoId:openingSource,titulo:'Abertura',artista:'Artista',nomeVersao:'Abertura',duracao:null,xEmLives:9},segmentos:[{tipo:'bloco',blocoId:block,nome:'Bloco com abertura',itens:[item(middle,middleSource,'Meio','base-meio'),item(end,endSource,'Fim','base-fim')]}]}; const saved=await app.inject({method:'PUT',url:`/api/v1/live-drafts/${draft.id}`,payload:{composicao:payload}}); assert.equal(saved.statusCode,200); assert.deepEqual(saved.json<any>().rascunho.composicao.segmentos[0].itens.map((x:any)=>x.musicaId),[middle,end]); assert.equal((db.prepare('SELECT x_em_lives FROM musicas WHERE id=?').get(opening) as any).x_em_lives,9); await app.close(); db.close();
});

test('F8.1 não oferece bloco somente com abertura e rejeita seu snapshot vazio', async () => {
  const {db,app}=fixture(); const opening=createMusic(db,{artista:'A',titulo:'Intro',ativo:true}); const source=addSource(db,opening,{nome:'Y',tipo:'youtube',referencia:'https://youtu.be/intro',abertura:true,principal:true}); const block=createBlock(db,{nome:'Só intro'}); addBlockMusic(db,block,opening); const draft=(await app.inject({method:'POST',url:'/api/v1/live-drafts'})).json<any>().rascunho; assert.equal(draft.opcoes.blocos.length,1); const response=await app.inject({method:'PUT',url:`/api/v1/live-drafts/${draft.id}`,payload:{composicao:{abertura:{musicaId:opening,versaoId:source,titulo:'Intro',artista:'A',nomeVersao:'Y',duracao:null,xEmLives:0},segmentos:[{tipo:'bloco',blocoId:block,nome:'Só intro',itens:[]}]}}}); assert.equal(response.statusCode,409); await app.close(); db.close();
});

test('F8.1 remove bloco inteiro quando qualquer item está inativo ou sem mídia reproduzível', async () => {
  const {db,app}=fixture(); const active=createMusic(db,{artista:'A',titulo:'Ativa',ativo:true}); addSource(db,active,{nome:'Y',tipo:'youtube',referencia:'https://youtu.be/a',principal:true}); const active2=createMusic(db,{artista:'A',titulo:'Ativa dois',ativo:true}); addSource(db,active2,{nome:'Y',tipo:'youtube',referencia:'https://youtu.be/a2',principal:true}); const inactive=createMusic(db,{artista:'A',titulo:'Inativa',ativo:true}); addSource(db,inactive,{nome:'Y',tipo:'youtube',referencia:'https://youtu.be/i',principal:true}); const invalid=createMusic(db,{artista:'A',titulo:'Sem mídia',ativo:true}); addSource(db,invalid,{nome:'Áudio',tipo:'audio',referencia:'musicas/not-found.mp3',principal:true}); const badInactive=createBlock(db,{nome:'Bloco inativo'}); addBlockMusic(db,badInactive,active); db.prepare('INSERT INTO musicas_do_bloco(bloco_id,musica_id,ordem,criada_em) VALUES(?,?,?,?)').run(badInactive,inactive,2,new Date().toISOString()); const badMedia=createBlock(db,{nome:'Bloco sem mídia'}); addBlockMusic(db,badMedia,active2); db.prepare('INSERT INTO musicas_do_bloco(bloco_id,musica_id,ordem,criada_em) VALUES(?,?,?,?)').run(badMedia,invalid,2,new Date().toISOString()); db.prepare('UPDATE musicas SET status_ativo=0 WHERE id=?').run(inactive); const draft=(await app.inject({method:'POST',url:'/api/v1/live-drafts'})).json<any>().rascunho; assert.deepEqual(draft.opcoes.blocos,[]); await app.close(); db.close();
});

test('F8.1 usa musicaId para duplicidade e não confunde músicas com a mesma musicaBase', async () => {
  const {db,app}=fixture(); const a=createMusic(db,{artista:'A',titulo:'Uma',ativo:true,musicaBase:'mesma-base'}); const as=addSource(db,a,{nome:'Y',tipo:'youtube',referencia:'https://youtu.be/a',principal:true}); const b=createMusic(db,{artista:'B',titulo:'Duas',ativo:true,musicaBase:'mesma-base'}); const bs=addSource(db,b,{nome:'Y',tipo:'youtube',referencia:'https://youtu.be/b',principal:true}); const draft=(await app.inject({method:'POST',url:'/api/v1/live-drafts'})).json<any>().rascunho; const make=(id:string,source:string,title:string)=>({tipo:'musica',...item(id,source,title,'mesma-base')}); let r=await app.inject({method:'PUT',url:`/api/v1/live-drafts/${draft.id}`,payload:{composicao:{abertura:null,segmentos:[make(a,as,'Uma'),make(b,bs,'Duas')]}}}); assert.equal(r.statusCode,200); r=await app.inject({method:'PUT',url:`/api/v1/live-drafts/${draft.id}`,payload:{composicao:{abertura:null,segmentos:[make(a,as,'Uma'),make(a,as,'Uma novamente')]}}}); assert.equal(r.statusCode,409); assert.match(r.json<any>().error,/já está/); await app.close(); db.close();
});
