// @ts-nocheck
// Production repository boundary. SQL migrations and their executor remain independent.
import '../runtime.mjs';
import { DatabaseSync } from 'node:sqlite';
import { mkdirSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createDrizzleClient } from './client.js';

const stamp = () => new Date().toISOString();
const columns = { artista:'artista', titulo:'titulo', musicaBase:'musica_base', status:'status', statusAtivo:'status_ativo', observacoes:'observacoes', generoPrimario:'genero_primario', generoSecundario:'genero_secundario', xEmLives:'x_em_lives', origem:'origem', autoral:'autoral', ativo:'ativo', duracao:'duracao', vibePrincipal:'vibe_principal', vibeSecundaria:'vibe_secundaria', temperaturaDePalco:'temperatura_de_palco', bloco:'bloco', clima:'clima', letra:'letra_caminho', letraCaminho:'letra_caminho' };
const nullable = new Set(['musicaBase','status','observacoes','generoPrimario','generoSecundario','origem','duracao','vibePrincipal','vibeSecundaria','temperaturaDePalco','bloco','clima','letra','letraCaminho']);
const bool = value => value ? 1 : 0;
const canonicalStatus = row => 'status_ativo' in row ? Boolean(row.status_ativo) : ('ativo' in row ? Boolean(row.ativo) : row.status === null || row.status === undefined || row.status === 'OK');
const music = row => row && ({ ...row, autoral:Boolean(row.autoral), ativo:'ativo' in row ? Boolean(row.ativo) : canonicalStatus(row), statusV1:canonicalStatus(row), fontes:[] });
let invocationCount = 0;
function useDrizzleRepository(db) {
  invocationCount++;
  // The adapter is attached by openDatabase and points at this exact SQLite
  // connection. Keeping it here makes repository use observable and prevents
  // a second database or migration path from being introduced.
  return db.__drizzle ?? createDrizzleClient(db);
}
export function getRepositoryInvocationCount() { return invocationCount; }

export function transaction(db, fn) { db.exec('BEGIN IMMEDIATE'); try { const value = fn(); db.exec('COMMIT'); return value; } catch (error) { db.exec('ROLLBACK'); throw error; } }
export function openDatabase(file) {
  mkdirSync(dirname(file), { recursive:true }); const db = new DatabaseSync(file);
  db.exec('PRAGMA foreign_keys = ON'); db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (nome TEXT PRIMARY KEY, aplicada_em TEXT NOT NULL)');
  const folder = new URL('../../migrations/', import.meta.url);
  for (const name of readdirSync(folder).filter(x=>x.endsWith('.sql')).sort()) if (!db.prepare('SELECT 1 FROM schema_migrations WHERE nome=?').get(name)) transaction(db, () => { db.exec(readFileSync(join(folder.pathname,name),'utf8')); db.prepare('INSERT INTO schema_migrations(nome,aplicada_em) VALUES (?,?)').run(name,stamp()); });
  Object.defineProperty(db, '__drizzle', { value: createDrizzleClient(db), enumerable: false });
  return db;
}
function sources(db, id) { return db.prepare('SELECT * FROM fontes_musica WHERE musica_id=? ORDER BY ordem,id').all(id).map(x=>({...x,principal:Boolean(x.principal),abertura:Boolean(x.abertura)})); }
export function getMusic(db,id) { useDrizzleRepository(db); const result=music(db.prepare('SELECT * FROM musicas WHERE id=?').get(id)); if(result) result.fontes=sources(db,id); return result||null; }
export function listMusic(db, filters={}) {
  useDrizzleRepository(db);
  let sql='SELECT * FROM musicas WHERE 1=1', args=[];
  if(filters.activeOnly === true) sql += ' AND status_ativo=1';
  if(filters.ativo !== undefined && filters.ativo !== '') { sql+=' AND ativo=?'; args.push(filters.ativo===true||filters.ativo==='true'?1:0); }
  if(filters.statusV1 !== undefined && filters.statusV1 !== '') { sql+=' AND status_ativo=?'; args.push(filters.statusV1===true||filters.statusV1==='true'?1:0); }
  for(const field of ['status','bloco','clima']) if(filters[field] !== undefined && filters[field] !== '') { sql+=` AND ${field}=?`; args.push(filters[field]); }
  if(filters.autoral !== undefined && filters.autoral !== '') { sql+=' AND autoral=?'; args.push(filters.autoral===true||filters.autoral==='true'?1:0); }
  if(filters.q) { sql+=' AND (titulo LIKE ? COLLATE NOCASE OR artista LIKE ? COLLATE NOCASE)'; args.push(`%${filters.q}%`,`%${filters.q}%`); }
  return db.prepare(sql+' ORDER BY artista COLLATE NOCASE,titulo COLLATE NOCASE').all(...args).map(row=>{const out=music(row);out.fontes=sources(db,row.id);return out;});
}
function valueFor(key,value) { if(key==='autoral'||key==='ativo'||key==='statusAtivo') return bool(value); if(key==='xEmLives') return Number(value); return value; }
export function createMusic(db,input) {
  useDrizzleRepository(db);
  if(!input?.artista || !input?.titulo) throw new Error('artista e titulo são obrigatórios');
  const id=input.id||randomUUID(), at=stamp(), fields=[], values=[];
  for(const [key,column] of Object.entries(columns)) if(key==='letraCaminho' || !(key in input)) continue; else { fields.push(column); values.push(valueFor(key,input[key])); }
  if(!fields.includes('musica_base')) { fields.push('musica_base'); values.push(input.titulo); } if(!fields.includes('x_em_lives')) { fields.push('x_em_lives'); values.push(0); } if(!fields.includes('autoral')) { fields.push('autoral'); values.push(0); } if(!fields.includes('ativo')) { fields.push('ativo'); values.push(input.ativo === undefined ? 1 : bool(input.ativo)); } if(!fields.includes('status_ativo')) { fields.push('status_ativo'); values.push(input.statusAtivo !== undefined ? bool(input.statusAtivo) : typeof input.status === 'boolean' ? bool(input.status) : input.ativo !== undefined ? bool(input.ativo) : input.status === undefined || input.status === null || input.status === 'OK' ? 1 : 0); }
  db.prepare(`INSERT INTO musicas(id,${fields.join(',')},criada_em,atualizada_em) VALUES (${Array(fields.length+3).fill('?').join(',')})`).run(id,...values,at,at); return id;
}
export function updateMusic(db,id,input) { useDrizzleRepository(db);
  if(!getMusic(db,id)) return null; const sets=[], values=[];
  for(const [key,column] of Object.entries(columns)) { if(key==='letraCaminho'|| !(key in input)) continue; if(input[key]===null && !nullable.has(key)) throw new Error(`${key} não aceita null`); sets.push(`${column}=?`); values.push(valueFor(key,input[key])); }
  if(!sets.length) return getMusic(db,id); db.prepare(`UPDATE musicas SET ${sets.join(',')},atualizada_em=? WHERE id=?`).run(...values,stamp(),id); return getMusic(db,id);
}
export function saveMusic(db,input) { return input.id && getMusic(db,input.id) ? (updateMusic(db,input.id,input),input.id) : createMusic(db,input); }
export function removeMusic(db,id) { useDrizzleRepository(db); return db.prepare('DELETE FROM musicas WHERE id=?').run(id).changes===1; }
export function addSource(db,musicId,input) {
  useDrizzleRepository(db);
  if(!getMusic(db,musicId)) throw new Error('Música não encontrada'); if(!['youtube','audio','video'].includes(input.tipo)||!input.referencia) throw new Error('Fonte inválida');
  const count=sources(db,musicId).length, id=input.id||randomUUID(), at=stamp(), principal=input.principal===undefined?count===0:Boolean(input.principal), ordem=input.ordem===undefined?count+1:Number(input.ordem);
  if(principal) db.prepare('UPDATE fontes_musica SET principal=0,atualizada_em=? WHERE musica_id=?').run(at,musicId);
  db.prepare('INSERT INTO fontes_musica(id,musica_id,nome,tipo,referencia,principal,ordem,duracao,abertura,criada_em,atualizada_em) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,musicId,input.nome||'Referência',input.tipo,input.referencia,bool(principal),ordem,input.duracao??null,bool(input.abertura),at,at); return id;
}
export const saveSource=addSource;
export function updateSource(db,musicId,sourceId,input) { const old=db.prepare('SELECT * FROM fontes_musica WHERE id=? AND musica_id=?').get(sourceId,musicId); if(!old) return null; const allowed=['nome','tipo','referencia','duracao','abertura','ordem'], sets=[], values=[]; for(const key of allowed) if(key in input){ if(key==='tipo'&&!['youtube','audio','video'].includes(input[key])) throw new Error('Tipo de fonte inválido'); if(key==='ordem' && (!Number.isInteger(input[key]) || input[key] < 1)) throw new Error('Ordem inválida'); sets.push(`${key}=?`);values.push(key==='abertura'?bool(input[key]):input[key]); } if(input.principal===true) { db.prepare('UPDATE fontes_musica SET principal=0 WHERE musica_id=?').run(musicId); sets.push('principal=1'); } if(!sets.length)return {...old,principal:Boolean(old.principal),abertura:Boolean(old.abertura)}; db.prepare(`UPDATE fontes_musica SET ${sets.join(',')},atualizada_em=? WHERE id=?`).run(...values,stamp(),sourceId); return sources(db,musicId).find(x=>x.id===sourceId); }
export function removeSource(db,musicId,sourceId) { return db.prepare('DELETE FROM fontes_musica WHERE id=? AND musica_id=?').run(sourceId,musicId).changes===1; }
export function setPrimarySource(db,musicId,sourceId) { if(!db.prepare('SELECT 1 FROM fontes_musica WHERE id=? AND musica_id=?').get(sourceId,musicId)) return false; transaction(db,()=>{db.prepare('UPDATE fontes_musica SET principal=0 WHERE musica_id=?').run(musicId);db.prepare('UPDATE fontes_musica SET principal=1,atualizada_em=? WHERE id=?').run(stamp(),sourceId);});return true; }
export function reorderSources(db,musicId,ids) { const current=sources(db,musicId); if(!Array.isArray(ids)||ids.length!==current.length||new Set(ids).size!==ids.length||ids.some(id=>!current.some(x=>x.id===id))) throw new Error('Ordem inválida'); transaction(db,()=>{ids.forEach((id,index)=>db.prepare('UPDATE fontes_musica SET ordem=?,atualizada_em=? WHERE id=?').run(-(index+1),stamp(),id));ids.forEach((id,index)=>db.prepare('UPDATE fontes_musica SET ordem=?,atualizada_em=? WHERE id=?').run(index+1,stamp(),id));}); return sources(db,musicId); }
export function setLyrics(db,id,path) { return updateMusic(db,id,{letra:path}); }
export function saveMusicRegistration(db, input) {
  return transaction(db, () => {
    const existing = input.id ? getMusic(db, input.id) : null;
    const status = input.status ?? input.ativo ?? true;
    const id = existing ? input.id : createMusic(db, { id: input.id, artista: input.artista, titulo: input.titulo, generoPrimario: input.genero ?? null, origem: input.origem ?? null, observacoes: input.observacoes ?? null, autoral: input.autoral, statusAtivo: status });
    if (existing) updateMusic(db, id, { artista: input.artista, titulo: input.titulo, generoPrimario: input.genero ?? null, origem: input.origem ?? null, observacoes: input.observacoes ?? null, autoral: input.autoral, statusAtivo: status });
    if ('letraCaminho' in input) updateMusic(db, id, { letra: input.letraCaminho ?? null });
    const versions = [...input.versoes].sort((a, b) => a.ordem - b.ordem);
    if (versions.some((version, index) => version.ordem !== index + 1)) throw new Error('As ordens devem começar em 1 e ser consecutivas');
    if (new Set(versions.map((version) => version.ordem)).size !== versions.length) throw new Error('Ordens duplicadas');
    db.prepare('DELETE FROM fontes_musica WHERE musica_id=?').run(id);
    for (const version of versions) addSource(db, id, { id: version.id, nome: version.nome, tipo: version.tipo, referencia: version.referencia, ordem: version.ordem, duracao: version.duracao ?? null, abertura: version.abertura, principal: version.ordem === 1 });
    return id;
  });
}
export function getMusicRegistrationArtifacts(db, id) {
  useDrizzleRepository(db);
  const row = getMusic(db, id);
  if (!row) return null;
  const blockLinks = db.prepare('SELECT bloco_id, ordem FROM musicas_do_bloco WHERE musica_id=? ORDER BY bloco_id, ordem').all(id);
  const liveLinks = db.prepare('SELECT live_id, id AS item_id FROM itens_da_live WHERE musica_id=? ORDER BY live_id, ordem').all(id);
  const localReferences = row.fontes
    .filter((source) => source.tipo === 'audio' || source.tipo === 'video')
    .map((source) => ({ kind: source.tipo, reference: source.referencia }));
  if (row.letra_caminho) localReferences.push({ kind: 'lyrics', reference: row.letra_caminho });
  const shared = localReferences.filter(({ reference }) => {
    if (reference.startsWith('letras/')) return Boolean(db.prepare('SELECT 1 FROM musicas WHERE letra_caminho=? AND id<>?').get(reference, id));
    return Boolean(db.prepare('SELECT 1 FROM fontes_musica WHERE referencia=? AND musica_id<>? AND tipo IN (\'audio\',\'video\')').get(reference, id));
  });
  return { music: row, blockLinks, liveLinks, localReferences, sharedReferences: shared };
}
export function removeMusicRegistration(db, id) {
  const artifacts = getMusicRegistrationArtifacts(db, id);
  if (!artifacts) return null;
  return transaction(db, () => {
    db.prepare('DELETE FROM musicas_do_bloco WHERE musica_id=?').run(id);
    db.prepare('DELETE FROM fontes_musica WHERE musica_id=?').run(id);
    db.prepare('DELETE FROM musicas WHERE id=?').run(id);
    return artifacts;
  });
}
export function exportCatalog(db) { return { formato:'live-console.catalogo/v1', exportadoEm:stamp(), musicas:listMusic(db).map(song=>({id:song.id,artista:song.artista,titulo:song.titulo,musicaBase:song.musica_base,status:canonicalStatus(song),observacoes:song.observacoes,genero:song.genero_primario,xEmLives:song.x_em_lives,origem:song.origem,autoral:song.autoral,letraCaminho:song.letra_caminho,versoes:song.fontes.map(({id,musica_id,criada_em,atualizada_em,principal,...f})=>f)})) }; }
function liveItems(db,id) { return db.prepare(`SELECT i.*,m.artista,m.titulo,m.letra_caminho,m.x_em_lives FROM itens_da_live i JOIN musicas m ON m.id=i.musica_id WHERE i.live_id=? ORDER BY i.ordem`).all(id); }
export function getLive(db,id) { useDrizzleRepository(db); const live=db.prepare('SELECT * FROM lives WHERE id=?').get(id); return live?{...live,status:live.status==='finalizada'?'executado':live.status,itens:liveItems(db,id)}:null; }
export function listLives(db) { useDrizzleRepository(db); return db.prepare('SELECT * FROM lives ORDER BY criada_em DESC').all().map(x=>({...x,status:x.status==='finalizada'?'executado':x.status,itens:liveItems(db,x.id)})); }
export function createLive(db,input={}) { useDrizzleRepository(db); if(!input.titulo?.trim()) throw new Error('titulo é obrigatório'); const id=input.id||randomUUID(), at=stamp(); db.prepare('INSERT INTO lives(id,titulo,data,status,observacoes,criada_em,atualizada_em) VALUES(?,?,?,?,?,?,?)').run(id,input.titulo.trim(),input.data??null,'rascunho',input.observacoes??null,at,at); return id; }
export function updateLive(db,id,input) { const old=getLive(db,id);if(!old)return null;if(old.status!=='rascunho')throw new Error('Somente rascunhos podem ser editados');const sets=[],values=[];for(const key of ['titulo','data','observacoes'])if(key in input){sets.push(`${key}=?`);values.push(input[key]);}if(!sets.length)return old;db.prepare(`UPDATE lives SET ${sets.join(',')},atualizada_em=? WHERE id=?`).run(...values,stamp(),id);return getLive(db,id); }
export function closeLive(db,id) { const live=getLive(db,id);if(!live)throw new Error('Live não encontrada');if(live.status!=='rascunho')throw new Error('Somente rascunhos podem ser fechados');if(!live.itens.length)throw new Error('O repertório precisa de músicas');const at=stamp();db.prepare("UPDATE lives SET status='fechado',fechado_em=?,atualizada_em=? WHERE id=?").run(at,at,id);return getLive(db,id); }
export function duplicateLive(db,id,input={}) { const source=getLive(db,id);if(!source)throw new Error('Live não encontrada');if(!['fechado','executado','finalizada','encerrada'].includes(source.status))throw new Error('Somente repertórios fechados ou executados podem ser duplicados');const newId=createLive(db,{titulo:input.titulo||`${source.titulo} · cópia`,data:input.data??source.data,observacoes:source.observacoes});const copied=[],omitted=[];transaction(db,()=>{for(const item of source.itens){const song=getMusic(db,item.musica_id);if(!song){omitted.push({musicaId:item.musica_id,motivo:'música ausente no catálogo'});continue;}if(item.bloco_id&&!getBlock(db,item.bloco_id))omitted.push({blocoId:item.bloco_id,motivo:'bloco ausente no catálogo'});try{const itemId=addLiveItem(db,newId,{musicaId:item.musica_id,referenciaReproducao:item.referencia_reproducao,tipoReproducao:item.tipo_reproducao,duracaoPlanejada:item.duracao_planejada,blocoId:item.bloco_id,ehAbertura:item.eh_abertura});copied.push(itemId);}catch(error){omitted.push({musicaId:item.musica_id,motivo:(error as Error).message});}}});return {live:getLive(db,newId),copiados:copied,omitidos:omitted}; }
export function removeLive(db,id) { return db.prepare('DELETE FROM lives WHERE id=?').run(id).changes===1; }
export function addLiveItem(db,liveId,input) { const live=getLive(db,liveId),musicRow=getMusic(db,input.musicaId);if(!live)throw new Error('Live não encontrada');if(!['rascunho','em_execucao'].includes(live.status))throw new Error('Repertório não aceita novas músicas');if(live.itens.some(x=>x.musica_id===input.musicaId))throw new Error('Música já está no repertório');if(input.ehAbertura&&live.itens.length)throw new Error('A abertura deve ser a primeira posição');if(!musicRow)throw new Error('Música não encontrada');const source=musicRow.fontes.find(x=>x.referencia===input.referenciaReproducao && x.tipo===input.tipoReproducao);if(!source)throw new Error('Referência de reprodução não pertence à música');const id=input.id||randomUUID(),at=stamp(),order=live.itens.length+1;db.prepare('INSERT INTO itens_da_live(id,live_id,musica_id,referencia_reproducao,tipo_reproducao,ordem,duracao_planejada,observacao,interacoes,bloco_id,eh_abertura,referencia_snapshot,criada_em,atualizada_em) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,liveId,input.musicaId,input.referenciaReproducao,input.tipoReproducao,order,input.duracaoPlanejada??source.duracao??musicRow.duracao??null,input.observacao??null,input.interacoes??null,input.blocoId??null,input.ehAbertura?1:0,input.referenciaReproducao,at,at);return id; }
export function updateLiveItem(db,liveId,itemId,input) { const live=getLive(db,liveId);if(live?.status!=='rascunho')throw new Error('Somente rascunhos podem ser editados');const old=db.prepare('SELECT * FROM itens_da_live WHERE id=? AND live_id=?').get(itemId,liveId);if(!old)return null;const sets=[],values=[];for(const [key,column] of [['referenciaReproducao','referencia_reproducao'],['tipoReproducao','tipo_reproducao'],['duracaoPlanejada','duracao_planejada'],['observacao','observacao'],['interacoes','interacoes']])if(key in input){sets.push(`${column}=?`);values.push(input[key]);}if('referenciaReproducao'in input||'tipoReproducao'in input){const ref=input.referenciaReproducao??old.referencia_reproducao,type=input.tipoReproducao??old.tipo_reproducao;if(!getMusic(db,old.musica_id).fontes.some(x=>x.referencia===ref&&x.tipo===type))throw new Error('Referência de reprodução não pertence à música');}if(sets.length)db.prepare(`UPDATE itens_da_live SET ${sets.join(',')},atualizada_em=? WHERE id=?`).run(...values,stamp(),itemId);return liveItems(db,liveId).find(x=>x.id===itemId)||null; }
export function removeLiveItem(db,liveId,itemId) { const live=getLive(db,liveId);if(live?.status==='em_execucao')throw new Error('Músicas não podem ser removidas durante a execução');return transaction(db,()=>{const removed=db.prepare('DELETE FROM itens_da_live WHERE id=? AND live_id=?').run(itemId,liveId).changes===1;if(removed)liveItems(db,liveId).forEach((x,index)=>db.prepare('UPDATE itens_da_live SET ordem=? WHERE id=?').run(index+1,x.id));return removed;}); }
export function reorderLiveItems(db,liveId,ids) { const current=liveItems(db,liveId);if(!Array.isArray(ids)||ids.length!==current.length||new Set(ids).size!==ids.length||ids.some(id=>!current.some(x=>x.id===id)))throw new Error('Ordem inválida');const opening=current.find(x=>x.eh_abertura);if(opening&&opening.id!==ids[0])throw new Error('A abertura deve permanecer na primeira posição');return transaction(db,()=>{ids.forEach((id,index)=>db.prepare('UPDATE itens_da_live SET ordem=? WHERE id=?').run(-(index+1),id));ids.forEach((id,index)=>db.prepare('UPDATE itens_da_live SET ordem=?,atualizada_em=? WHERE id=?').run(index+1,stamp(),id));return liveItems(db,liveId);}); }
export function exportLegacyLive(db,id) { const live=getLive(db,id);if(!live)return null;return {titulo:live.titulo,data:live.data,observacao:live.observacoes,musicas:live.itens.map(item=>{const out={titulo:item.titulo,artista:item.artista,fonte:item.tipo_reproducao,letra:item.letra_caminho,observacao:item.observacao,interacoes:item.interacoes,duracao:item.duracao_planejada};if(item.tipo_reproducao==='youtube')out.youtube=item.referencia_reproducao;else out.arquivo=item.referencia_reproducao;return out;})}; }
function blocoSongs(db,id) { return db.prepare('SELECT m.*, b.ordem FROM musicas_do_bloco b JOIN musicas m ON m.id=b.musica_id WHERE b.bloco_id=? ORDER BY b.ordem').all(id).map(row=>({...music(row),fontes:sources(db,row.id)})); }
export function listBlocks(db) { useDrizzleRepository(db); return db.prepare('SELECT b.*, count(m.musica_id) quantidade_musicas FROM blocos b LEFT JOIN musicas_do_bloco m ON m.bloco_id=b.id GROUP BY b.id ORDER BY b.nome COLLATE NOCASE').all(); }
export function getBlock(db,id) { useDrizzleRepository(db); const block=db.prepare('SELECT * FROM blocos WHERE id=?').get(id); return block?{...block,musicas:blocoSongs(db,id)}:null; }
export function createBlock(db,input) { useDrizzleRepository(db); const id=input.id||randomUUID(),at=stamp();db.prepare('INSERT INTO blocos(id,nome,descricao,criada_em,atualizada_em) VALUES(?,?,?,?,?)').run(id,input.nome.trim(),input.descricao??null,at,at);return id; }
export function updateBlock(db,id,input) { const old=getBlock(db,id);if(!old)return null;const sets=[],values=[];for(const key of ['nome','descricao'])if(key in input){sets.push(`${key}=?`);values.push(key==='nome'?input[key].trim():input[key]);}if(!sets.length)return old;db.prepare(`UPDATE blocos SET ${sets.join(',')},atualizada_em=? WHERE id=?`).run(...values,stamp(),id);return getBlock(db,id); }
export function removeBlock(db,id) { useDrizzleRepository(db);return db.prepare('DELETE FROM blocos WHERE id=?').run(id).changes===1; }
export function addBlockMusic(db,blockId,musicId) { useDrizzleRepository(db);if(!getBlock(db,blockId))throw new Error('Bloco não encontrado');const song=getMusic(db,musicId);if(!song)throw new Error('Música não encontrada');if(!song.statusV1)throw new Error('Música inativa não pode ser adicionada a um bloco');return transaction(db,()=>{if(db.prepare('SELECT 1 FROM musicas_do_bloco WHERE bloco_id=? AND musica_id=?').get(blockId,musicId))throw new Error('Música já pertence ao bloco');const other=db.prepare('SELECT b.nome FROM musicas_do_bloco mb JOIN blocos b ON b.id=mb.bloco_id WHERE mb.musica_id=? AND mb.bloco_id<>? LIMIT 1').get(musicId,blockId);if(other)throw new Error(`Música já pertence ao bloco "${other.nome}"`);if(blocoSongs(db,blockId).length>=10)throw new Error('Bloco limitado a 10 músicas');const order=blocoSongs(db,blockId).length+1;db.prepare('INSERT INTO musicas_do_bloco(bloco_id,musica_id,ordem,criada_em) VALUES(?,?,?,?)').run(blockId,musicId,order,stamp());return getBlock(db,blockId);}); }
export function removeBlockMusic(db,blockId,musicId) { useDrizzleRepository(db);return transaction(db,()=>{const removed=db.prepare('DELETE FROM musicas_do_bloco WHERE bloco_id=? AND musica_id=?').run(blockId,musicId).changes===1;if(removed)blocoSongs(db,blockId).forEach((x,index)=>db.prepare('UPDATE musicas_do_bloco SET ordem=? WHERE bloco_id=? AND musica_id=?').run(index+1,blockId,x.id));return removed;}); }
export function reorderBlockMusic(db,blockId,ids) { useDrizzleRepository(db);const current=blocoSongs(db,blockId);if(ids.length!==current.length||new Set(ids).size!==ids.length||ids.some(id=>!current.some(x=>x.id===id)))throw new Error('Ordem inválida');return transaction(db,()=>{ids.forEach((id,index)=>db.prepare('UPDATE musicas_do_bloco SET ordem=? WHERE bloco_id=? AND musica_id=?').run(100000+index,blockId,id));ids.forEach((id,index)=>db.prepare('UPDATE musicas_do_bloco SET ordem=? WHERE bloco_id=? AND musica_id=?').run(index+1,blockId,id));return getBlock(db,blockId).musicas;}); }
export function listBlockMusicOptions(db,blockId,q='') { useDrizzleRepository(db);if(!getBlock(db,blockId))return null;const term=String(q).trim();const rows=db.prepare(`SELECT m.*, (SELECT mb.bloco_id FROM musicas_do_bloco mb WHERE mb.musica_id=m.id LIMIT 1) bloco_atual_id, (SELECT b.nome FROM musicas_do_bloco mb JOIN blocos b ON b.id=mb.bloco_id WHERE mb.musica_id=m.id LIMIT 1) bloco_atual_nome FROM musicas m WHERE (?='' OR m.titulo LIKE ? COLLATE NOCASE OR m.artista LIKE ? COLLATE NOCASE) ORDER BY m.artista COLLATE NOCASE,m.titulo COLLATE NOCASE`).all(term,`%${term}%`,`%${term}%`);return rows.map(row=>{const canonical=music(row);const currentId=row.bloco_atual_id??null;const sameBlock=currentId===blockId;const available=Boolean(canonical.statusV1)&&(!currentId||sameBlock);const motivo=!canonical.statusV1?'Música inativa':currentId&&!sameBlock?`Já pertence ao bloco "${row.bloco_atual_nome}"`:sameBlock?'Já está neste bloco':null;return {...canonical,blocoAtualId:currentId,blocoAtualNome:row.bloco_atual_nome??null,disponivel:available&& !sameBlock,motivo};}); }
export function addBlockToLive(db,liveId,blockId) { useDrizzleRepository(db);const live=getLive(db,liveId),block=getBlock(db,blockId);if(!live)throw new Error('Live não encontrada');if(live.status!=='rascunho')throw new Error('Live não está em rascunho');if(!block)throw new Error('Bloco não encontrado');return transaction(db,()=>{const existing=new Set(live.itens.map(x=>x.musica_id)), additions=[],ignored=[];for(const song of block.musicas){if(existing.has(song.id)){ignored.push(song.id);continue;}const source=song.fontes.find(x=>x.principal);if(!source)throw new Error('Música do bloco sem fonte principal válida');additions.push({song,source});existing.add(song.id);}const added=[];for(const {song,source} of additions)added.push(addLiveItem(db,liveId,{musicaId:song.id,referenciaReproducao:source.referencia,tipoReproducao:source.tipo,duracaoPlanejada:source.duracao??song.duracao??null}));return {adicionados:added,ignorados:ignored};}); }
function montagemCandidate(song,origin,criteria,used){const source=song.fontes.find(x=>x.principal);if(!song.statusV1)return {song,motivo:'status inativo'};if(!source)return {song,motivo:'sem referência principal'};if(used.has(song.id))return {song,motivo:'já está na live ou seleção'};const base=song.musica_base??song.titulo;if(used.has(`base:${base}`))return {song,motivo:'musicaBase repetida'};const text=[song.vibe_principal,song.vibe_secundaria,song.clima,song.bloco].filter(Boolean).join(' ').toLocaleLowerCase();if(criteria.vibe&&song.vibe_principal!==criteria.vibe&&song.vibe_secundaria!==criteria.vibe)return {song,motivo:'vibe não corresponde'};if(criteria.clima&&song.clima!==criteria.clima)return {song,motivo:'clima não corresponde'};if(criteria.objetivo&&!text.includes(criteria.objetivo.toLocaleLowerCase()))return {song,motivo:'objetivo não corresponde'};return {song,source,origem:origin,base};}
export function previewMontagem(db,liveId,criteria){useDrizzleRepository(db);const live=getLive(db,liveId);if(!live)throw new Error('Live não encontrada');if(live.status!=='rascunho')throw new Error('Live não está em rascunho');const used=new Set(live.itens.map(x=>x.musica_id)), ignored=[], ordered=[];for(const blockId of criteria.blocoIds??[]){const block=getBlock(db,blockId);if(!block){ignored.push({blocoId,motivo:'bloco inexistente'});continue;}for(const song of block.musicas)ordered.push({song,origem:'bloco prioritário'});}const seen=new Set(ordered.map(x=>x.song.id));for(const song of listMusic(db,{activeOnly:true}).sort((a,b)=>`${a.artista}\u0000${a.titulo}\u0000${a.id}`.localeCompare(`${b.artista}\u0000${b.titulo}\u0000${b.id}`)))if(!seen.has(song.id))ordered.push({song,origem:'complemento do catálogo'});const eligible=[];for(const item of ordered){const c=montagemCandidate(item.song,item.origem,criteria,used);if(c.motivo){ignored.push({musicaId:item.song.id,motivo:c.motivo});continue;}eligible.push(c);}const autos=eligible.filter(x=>x.song.autoral), non=eligible.filter(x=>!x.song.autoral), chosen=[];for(const x of autos.slice(0,criteria.autorais)){chosen.push(x);used.add(x.song.id);used.add(`base:${x.base}`);}for(const x of non){if(chosen.length>=criteria.quantidade)break;if(used.has(`base:${x.base}`)){ignored.push({musicaId:x.song.id,motivo:'musicaBase repetida'});continue;}chosen.push(x);used.add(x.song.id);used.add(`base:${x.base}`);}const conflicts=[];if(autos.length<criteria.autorais)conflicts.push('autorais elegíveis insuficientes');if(chosen.length<criteria.quantidade)conflicts.push('músicas elegíveis insuficientes');return {criterios:criteria,quantidade:{pedida:criteria.quantidade,disponivel:eligible.length,selecionada:chosen.length},autorais:{pedidas:criteria.autorais,disponiveis:autos.length,selecionadas:chosen.filter(x=>x.song.autoral).length},selecionadas:chosen.map(x=>({musicaId:x.song.id,artista:x.song.artista,titulo:x.song.titulo,referencia:x.source.referencia,tipo:x.source.tipo,origem:x.origem})),ignorados:ignored,conflitos:conflicts,regras:['status booleano ativo','fonte principal válida','musicaBase única literal','blocos na ordem enviada','complemento por artista, título e id','objetivo busca textual em vibe, clima e bloco histórico']};}
export function confirmMontagem(db,liveId,criteria){const preview=previewMontagem(db,liveId,criteria);if(preview.conflitos.length)throw Object.assign(new Error('Critérios impossíveis'),{preview});return transaction(db,()=>{const fresh=previewMontagem(db,liveId,criteria);if(fresh.conflitos.length)throw Object.assign(new Error('Critérios impossíveis'),{preview:fresh});const added=[];for(const item of fresh.selecionadas)added.push(addLiveItem(db,liveId,{musicaId:item.musicaId,referenciaReproducao:item.referencia,tipoReproducao:item.tipo}));const at=stamp();db.prepare('INSERT INTO montagens_da_live(live_id,criterios_json,resultado_json,criada_em,atualizada_em) VALUES(?,?,?,?,?) ON CONFLICT(live_id) DO UPDATE SET criterios_json=excluded.criterios_json,resultado_json=excluded.resultado_json,atualizada_em=excluded.atualizada_em').run(liveId,JSON.stringify(criteria),JSON.stringify(fresh),at,at);return {itens:added,criterios:criteria,resultado:fresh};});}
export function getMontagem(db,liveId){const row=db.prepare('SELECT * FROM montagens_da_live WHERE live_id=?').get(liveId);return row?{...row,criterios:JSON.parse(row.criterios_json),resultado:JSON.parse(row.resultado_json)}:null;}
function execution(db,liveId){const live=getLive(db,liveId);if(!live)return null;const rows=db.prepare('SELECT * FROM execucao_itens_live WHERE live_id=?').all(liveId);const map=new Map(rows.map(x=>[x.item_id,x]));return {...live,execucao:live.itens.map(item=>map.get(item.id)??{item_id:item.id,musica_id:item.musica_id,estado:'pendente',referencia_usada:item.referencia_reproducao}),historico:rows.filter(x=>x.estado==='tocada').sort((a,b)=>(a.posicao_real??0)-(b.posicao_real??0)),resumo:{tocadas:rows.filter(x=>x.estado==='tocada').length,puladas:rows.filter(x=>x.estado==='pulada').length,pendentes:live.itens.length-rows.filter(x=>['tocada','pulada'].includes(x.estado)).length}};}
export function startExecution(db,liveId,key){const replay=db.prepare('SELECT dados_json FROM eventos_execucao_live WHERE idempotency_key=?').get(key);if(replay)return JSON.parse(replay.dados_json);return transaction(db,()=>{const live=getLive(db,liveId);if(!live)throw new Error('Live não encontrada');if(live.status!=='fechado')throw new Error('A live precisa estar fechada para iniciar');const at=stamp();db.prepare("UPDATE lives SET status='em_execucao',atualizada_em=? WHERE id=?").run(at,liveId);db.prepare('INSERT INTO execucao_lives(live_id,iniciada_em,atualizada_em,status) VALUES(?,?,?,?)').run(liveId,at,at,'ativa');const result=execution(db,liveId);db.prepare('INSERT INTO eventos_execucao_live(id,live_id,acao,idempotency_key,efeito_x_em_lives,dados_json,criada_em) VALUES(?,?,?,?,?,?,?)').run(randomUUID(),liveId,'iniciar',key,0,JSON.stringify(result),at);return result;});}
export function changeExecution(db,liveId,itemId,input){const replay=db.prepare('SELECT dados_json FROM eventos_execucao_live WHERE idempotency_key=?').get(input.idempotencyKey);if(replay)return JSON.parse(replay.dados_json);return transaction(db,()=>{const live=getLive(db,liveId);if(!live)throw new Error('Live não encontrada');if(live.status!=='em_execucao')throw new Error('Transição inválida');const item=live.itens.find(x=>x.id===itemId);if(!item)throw new Error('Item não encontrado');const old=db.prepare('SELECT * FROM execucao_itens_live WHERE live_id=? AND item_id=?').get(liveId,itemId)??{estado:'pendente'};if(input.acao==='tocada'&&old.estado!=='tocando')throw new Error('Play é obrigatório antes de marcar tocada');if(input.acao==='desfazer_tocada'&&(!input.confirmado||old.estado!=='tocada'))throw new Error('Confirmação explícita é obrigatória');const state=input.acao==='play'?'tocando':input.acao==='desfazer_tocada'?'pendente':input.acao;const at=stamp();const started=input.acao==='play'?(input.playEm??at):(old.tocada_em??null);const pos=input.posicaoReal??old.posicao_real??(db.prepare("SELECT COALESCE(MAX(posicao_real),0)+1 n FROM execucao_itens_live WHERE live_id=? AND estado='tocada'").get(liveId).n);const session=db.prepare('SELECT iniciada_em FROM execucao_lives WHERE live_id=?').get(liveId);const origin=new Date(item.criada_em).getTime()>new Date(session.iniciada_em).getTime()?'adicionada_durante_execucao':'planejada';db.prepare('INSERT INTO execucao_itens_live(live_id,item_id,musica_id,estado,executada_em,posicao_real,referencia_usada,observacao,atualizada_em,tocada_em,confirmada_em,origem) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(live_id,item_id) DO UPDATE SET estado=excluded.estado,executada_em=excluded.executada_em,posicao_real=excluded.posicao_real,referencia_usada=excluded.referencia_usada,observacao=excluded.observacao,atualizada_em=excluded.atualizada_em,tocada_em=excluded.tocada_em,confirmada_em=excluded.confirmada_em').run(liveId,itemId,item.musica_id,state,state==='tocada'?at:null,pos, input.referencia??item.referencia_reproducao,input.observacao??null,at,started,state==='tocada'?at:null,origin);const result={estado:state,efeitoXEmLives:0,execucao:execution(db,liveId)};db.prepare('INSERT INTO eventos_execucao_live(id,live_id,item_id,acao,idempotency_key,estado_anterior,estado_novo,efeito_x_em_lives,dados_json,criada_em) VALUES(?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),liveId,itemId,input.acao,input.idempotencyKey,old.estado,state,0,JSON.stringify(result),at);return result;});}
export function endExecution(db,liveId,key){const replay=db.prepare('SELECT dados_json FROM eventos_execucao_live WHERE idempotency_key=?').get(key);if(replay)return JSON.parse(replay.dados_json);return transaction(db,()=>{const live=getLive(db,liveId);if(!live)throw new Error('Live não encontrada');if(live.status==='executado')return execution(db,liveId);if(live.status!=='em_execucao')throw new Error('Transição inválida');const at=stamp();const played=db.prepare("SELECT DISTINCT musica_id FROM execucao_itens_live WHERE live_id=? AND estado='tocada'").all(liveId);let reconciled=0;for(const row of played){const musicaId=row['musica_id'];const existing=db.prepare('SELECT 1 FROM reconciliacoes_execucao WHERE sessao_id=? AND musica_id=?').get(liveId,musicaId);if(!existing){db.prepare('INSERT INTO reconciliacoes_execucao(sessao_id,musica_id,criada_em) VALUES(?,?,?)').run(liveId,musicaId,at);db.prepare('UPDATE musicas SET x_em_lives=x_em_lives+1,atualizada_em=? WHERE id=?').run(at,musicaId);reconciled++;}}db.prepare("UPDATE lives SET status='executado',executado_em=?,atualizada_em=? WHERE id=?").run(at,at,liveId);db.prepare('UPDATE execucao_lives SET encerrada_em=?,reconciliada_em=?,atualizada_em=?,status=\'encerrada\',chave_idempotencia=? WHERE live_id=?').run(at,at,at,key,liveId);const result=execution(db,liveId);db.prepare('INSERT INTO eventos_execucao_live(id,live_id,acao,idempotency_key,efeito_x_em_lives,dados_json,criada_em) VALUES(?,?,?,?,?,?,?)').run(randomUUID(),liveId,'encerrar',key,reconciled,JSON.stringify(result),at);return result;});}
export function executionHistory(db,liveId){const state=execution(db,liveId);if(!state)return null;return {...state,eventos:db.prepare('SELECT * FROM eventos_execucao_live WHERE live_id=? ORDER BY criada_em').all(liveId),sessao:db.prepare('SELECT * FROM execucao_lives WHERE live_id=?').get(liveId)??null};}
