import { integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const musicas = sqliteTable('musicas',{id:text().primaryKey(),artista:text().notNull(),titulo:text().notNull(),musicaBase:text('musica_base'),status:text(),observacoes:text(),generoPrimario:text('genero_primario'),generoSecundario:text('genero_secundario'),xEmLives:integer('x_em_lives').notNull(),origem:text(),autoral:integer().notNull(),duracao:integer(),vibePrincipal:text('vibe_principal'),vibeSecundaria:text('vibe_secundaria'),temperaturaDePalco:text('temperatura_de_palco'),bloco:text(),clima:text(),letraCaminho:text('letra_caminho'),criadaEm:text('criada_em').notNull(),atualizadaEm:text('atualizada_em').notNull()});
export const fontesMusica=sqliteTable('fontes_musica',{id:text().primaryKey(),musicaId:text('musica_id').notNull().references(()=>musicas.id),nome:text().notNull(),tipo:text().notNull(),referencia:text().notNull(),principal:integer().notNull(),ordem:integer().notNull(),duracao:integer(),criadaEm:text('criada_em').notNull(),atualizadaEm:text('atualizada_em').notNull()},t=>[uniqueIndex('uma_fonte_principal_por_musica').on(t.musicaId,t.principal)]);
export const lives=sqliteTable('lives',{id:text().primaryKey(),titulo:text().notNull(),data:text(),status:text().notNull(),observacoes:text(),criadaEm:text('criada_em').notNull(),atualizadaEm:text('atualizada_em').notNull()});
export const itensDaLive=sqliteTable('itens_da_live',{id:text().primaryKey(),liveId:text('live_id').notNull().references(()=>lives.id),musicaId:text('musica_id').notNull().references(()=>musicas.id),referenciaReproducao:text('referencia_reproducao').notNull(),tipoReproducao:text('tipo_reproducao').notNull(),ordem:integer().notNull(),duracaoPlanejada:integer('duracao_planejada'),observacao:text(),interacoes:text(),criadaEm:text('criada_em').notNull(),atualizadaEm:text('atualizada_em').notNull()});
export const schemaMigrations=sqliteTable('schema_migrations',{nome:text().primaryKey(),aplicadaEm:text('aplicada_em').notNull()});
export const blocos=sqliteTable('blocos',{id:text().primaryKey(),nome:text().notNull(),descricao:text(),criadaEm:text('criada_em').notNull(),atualizadaEm:text('atualizada_em').notNull()});
export const musicasDoBloco=sqliteTable('musicas_do_bloco',{blocoId:text('bloco_id').notNull().references(()=>blocos.id,{onDelete:'cascade'}),musicaId:text('musica_id').notNull().references(()=>musicas.id),ordem:integer().notNull(),criadaEm:text('criada_em').notNull()},t=>[uniqueIndex('musicas_do_bloco_ordem_unica').on(t.blocoId,t.ordem)]);
