import { existsSync } from 'node:fs';
import { isAbsolute, resolve } from 'node:path';
import { createMusic, listMusic, getMusic, updateMusic, addSource, transaction } from './db.mjs';
const identity = item => `${item.artista}\u0000${item.titulo}\u0000${item.musicaBase ?? item.titulo}`;
const sourceIdentity = source => `${source.tipo}\u0000${source.referencia}`;
const permitted = new Set(['youtube','audio','video']);
function compare(a,b){ return JSON.stringify(a)===JSON.stringify(b); }
function validate(item,index,report,storageRoot) { const errors=[]; if(!item||typeof item!=='object'||!item.artista||!item.titulo||!Array.isArray(item.fontes))errors.push('artista, titulo e fontes são obrigatórios'); let principal=0, seen=new Set(); for(const source of item?.fontes||[]){if(!source||!permitted.has(source.tipo)||!source.nome||!source.referencia) errors.push('fonte inválida'); if(source.principal)principal++; const k=sourceIdentity(source);if(seen.has(k))errors.push('referência duplicada');seen.add(k); if(typeof source.referencia==='string'&&isAbsolute(source.referencia)){report.caminhosLegados.push({index,referencia:source.referencia});(existsSync(resolve(storageRoot,source.referencia))?report.arquivosEncontrados:report.arquivosNaoEncontrados).push(source.referencia);}} if(principal>1)errors.push('mais de uma fonte principal');if(errors.length){report.rejeitadas.push({index,errors});return false;}return true; }
export function inspectImport(db,payload,{storageRoot=process.cwd()}={}) { const report={novas:[],atualizaveis:[],identicas:[],conflitantes:[],rejeitadas:[],referenciasNovas:0,referenciasExistentes:0,arquivosEncontrados:[],arquivosNaoEncontrados:[],caminhosLegados:[]}; report.inserted=report.novas;report.updated=report.atualizaveis;report.identical=report.identicas;report.rejected=report.rejeitadas;report.conflicts=report.conflitantes;report.legacyPaths=report.caminhosLegados;report.filesFound=report.arquivosEncontrados;report.filesMissing=report.arquivosNaoEncontrados;
 if(!payload||!Array.isArray(payload.musicas)){report.rejeitadas.push({index:null,errors:['musicas deve ser uma lista']});return report;} const existing=new Map(listMusic(db).map(x=>[identity(x),x])); payload.musicas.forEach((item,index)=>{if(!validate(item,index,report,storageRoot))return;const prior=existing.get(identity(item));if(!prior)report.novas.push(index);else { const oldSources=new Map(prior.fontes.map(x=>[sourceIdentity(x),x])); const fields={...item,fontes:undefined}; const oldFields={...prior,fontes:undefined}; const sourceChanges=item.fontes.some(x=>!oldSources.has(sourceIdentity(x))); item.fontes.forEach(x=>oldSources.has(sourceIdentity(x))?report.referenciasExistentes++:report.referenciasNovas++); if(compare(fields,oldFields)&&!sourceChanges)report.identicas.push(index);else if(item.id&&item.id!==prior.id)report.conflitantes.push({index,reason:'id não corresponde à identidade'});else report.atualizaveis.push(index); }}); return report; }
export function confirmImport(db,payload,options={}) { const preview=inspectImport(db,payload,options); if(preview.rejeitadas.length&&!options.partial)return {...preview,applied:false}; const rejected=new Set(preview.rejeitadas.map(x=>x.index)); const apply=()=>{const report={...preview,applied:true,created:0,updatedCount:0};for(const [index,item] of payload.musicas.entries()){if(rejected.has(index))continue;const prior=listMusic(db).find(x=>identity(x)===identity(item));let id;if(prior){id=prior.id;const patch={...item};delete patch.fontes; delete patch.xEmLives; updateMusic(db,id,patch);report.updatedCount++;}else {id=createMusic(db,item);report.created++;}const known=new Set((getMusic(db,id).fontes).map(sourceIdentity));for(const source of item.fontes)if(!known.has(sourceIdentity(source)))addSource(db,id,source);}return report;}; return options.partial?apply():transaction(db,apply); }
export { identity, sourceIdentity };
